### ISSUE TITLE
Use pure Rust GUI library?

### ISSUE THREAD

**Issue by eszlari** [ilya-zlobintsev/LACT#104]
Has it been considered to move to a pure Rust GUI library to simplify the deployment process?

One candidate could be iced-rs: https://github.com/iced-rs/iced (which seems to get some investment: https://www.phoronix.com/news/COSMIC-Desktop-Iced-Toolkit).

**Comment by ilya-zlobintsev** [comment]
Yes, I have looked into them, with iced and slint being the main candidates. However there are several problems with them:
- None of the toolkits are nearly as mature as GTK and have missing major features. For example iced doesn't have multi-window support: https://github.com/iced-rs/iced/issues/27
- They aren't well integrated with the system (except for slint which can use QT styling)

There is a new Rust toolkit being created every once in a while, but none of them have reached any widespread adoption.

GTK is one of the two de-facto "native" Linux graphical toolkits (with QT being the other one), looks consistent with other applications in the system and has widgets which users are familiar with. The gtk-rs bindings are also pretty good, which is why GTK was used instead of QT.

IMO the advantage of easier packaging (not depending on the system installation of GTK) does not outweigh the listed disadvantages. The situation would be different if this was a cross-platform app, but as it's Linux-only I really don't think using a Rust toolkit is worth it with the current state of things.
