### ISSUE TITLE
Fan control sliders should have text boxes for % values

### ISSUE THREAD

**Issue by 43615** [ilya-zlobintsev/LACT#238]
I have figured out that scrolling moves the sliders by exactly 5%, but this isn't exactly pretty.

**Comment by ilya-zlobintsev** [comment]
I know this isn't exactly a full solution, but if you use arrow keys you can adjust by 1%.

**Comment by bpjoestar** [comment]
Hey I love your Project. LACT works perfectly fine on openSUSE Tumbleweed and I'm very happy that your next Version will include an openSUSE Tumbleweed.rpm 

as @43615 mentioned, I would love a % slider as well, otherwise LACT is perfect! 
Thanks for the tip with the Arrow keys.

I'm no programmer, just created this account today.
Thanks for your work. @ilya-zlobintsev

**Comment by ilya-zlobintsev** [comment]
This has been implemented in https://github.com/ilya-zlobintsev/LACT/commit/d1acdde89caa00e2fa3b48fe55e0f7c7d2093529:
![image](https://github.com/ilya-zlobintsev/LACT/assets/22796665/7e7fc11d-3c14-469a-ac47-9e66a809b427)
