### ISSUE TITLE
Control contrast and saturation

### ISSUE THREAD

**Issue by haytham-med** [ilya-zlobintsev/LACT#261]
Hi, can you add the ability to control contrast and saturation to the app?

Thanks and keep up the good work

**Comment by ilya-zlobintsev** [comment]
I'm not entirely sure that display configuration is something that should be included in LACT, however there are two ways of doing it:
- Software colour configuration - this is problematic because on Wayland there is no standardized protocol for it, every compositor implements it in its own way, and support is inconsistent. On X11 some functionality is standard (gamma), but saturation is not, and has inconsistencies between gpu vendors (though this would probably not be a huge problem as this utility is AMD-focused)

  In both cases changing these settings is linked to the graphical session, which the LACT daemon currently does not interact with, so there would also need to be a way to link a system service running as root to a graphical session.
- Changing monitor settings in hardware via DDC - this is a lot more similar to how LACT currently interacts with GPU settings, except for monitors. This has the upside of being completely agnostic to any graphical sesesion regardless of the display server or desktop environment, and the settings are also saved in hardware, so there is no need to manage their persistence. The downside is that you will be limited by what the monitor exposes via DDC - not all settings are available on all monitors.

If this were to be implemented, then I would strongly prefer it to be the second option. However this would be more of a convenience feature, since you can already change those options in your monitor's OSD.

**Comment by haytham-med** [comment]
I would prefer a software oriented solution,  saturation was implemented using libvibrant a while ago on X11 but stopped working, On wayland contrast and saturation can be controlled in gnome via zoom accessibility, Also I saw a gnome extension that desaturates screen and applies color filters for blind.

Libvibrant was working on different desktop environments, also with different vendors: nvidia + amd

So I believe a working software-oriented solution for wayland can be done.
Thanks.

**Comment by haytham-med** [comment]
And i just discovered an extension from same author of Colorblind filters called CHC-E extension .
So I guess the current problem is to make it desktop independent .

**Comment by ilya-zlobintsev** [comment]
That gnome extension works by applying a custom GLSL shader onto the entire screen in the shell. This is extremely gnome-specific and isn't even display configuration, rather altering the image at an earlier stage.
KDE seems to support color configuration via ICC profiles, but doesn't have a more simplified interface for specifically setting the contrast or gamma.
wlroots (library used by sway) does support configuring the values through a custom protocol.

Supporting desktop-specific implementations is something that's out of scope for LACT. It's the same reason as why there aren't other display settings like resolution - this is something that's better handled by the desktop's configuration, or at least a different tool.
