### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by massatt212** [ilya-zlobintsev/LACT#267]
Dont you want to implement Nvidia and Intel into Lact? you got Green With Envy as a helper, maybe u can use it and add it to lact adding more to your Program.

**Comment by ilya-zlobintsev** [comment]
Nvidia support is out of scope for this project. It works completely differently from AMD, and I do not have the hardware to test it on. Use GreenWithEnvy instead, it achieves largely the same functionality as LACT.

Intel Arc GPUs don't seem to support overclocking under linux. Intel integrated GPUs do seem to expose some  functionality, but I'm not sure how useful it would be.

**Comment by ilya-zlobintsev** [comment]
LACT is not a product, it's a personal project that I work on in my free time.
Expanding it to support everything is not realistic, I don't think it would be fitting for the project, and I do not have the time, motivation or available hardware for it.

I'd rather have a limited scope of functionality (configuring AMD GPUs and showing info about them), and have that functionality be polished and well-tested, instead of adding too many features.

If Intel ARC GPUs get support for configuration on linux and i manage to get my hands on one, then I would consider adding support for them, as it would be interesting and there no other tools for it. But otherwise I'd like to avoid feature creep.
