### ISSUE TITLE
Make historical charts better accessible and some thoughts on GTK

### ISSUE THREAD

**Issue by frumble** [ilya-zlobintsev/LACT#316]
First: Thanks you very much for your important work!

The new historical data window is complicated to access. Why put it behind the strange hamburger menu? This should either be a tab in the UI or openable via a prominent button.
Speaking as a Plasma user, you toolkit choice is a little sad. Most gamers would be on Plasma sessions and the GTK toolbar is not only alien, the window is also hard to grab to move without key modifier. When I grab it on the toolbar buttons, the buttons get visually activated, making several tabs blue… That’s just crappy Gnome toolkit behavior.

**Comment by ilya-zlobintsev** [comment]
>  This should either be a tab in the UI or openable via a prominent button.

There is a big button for it next to the real-time stats:
![image](https://github.com/ilya-zlobintsev/LACT/assets/22796665/7ae38410-9e8e-4c83-b9c0-2e016fddc47d)

> Speaking as a Plasma user, you toolkit choice is a little sad.

LACT (at least in the default build) intentionally uses GTK4 without libadwaita so that it follows the system theme on any desktop by default. I develop the app on KDE myself and it uses the breeze theme. This style of toolbar is used in almost all modern GTK apps (which make up a significant portion, if not the majority of apps on the linux desktop), so i do not see how it is out of place.

Other than this, GTK is by far the most mature UI toolkit option that's available to reasonable use in Rust. QT is technically possible, but very inconvenient to use due to its reliance on C++ style OOP, which means you have to either use raw c bindings or wrap everything into complex macros that try to add inheritance on top of the rust type system. There are promising rust-native options such as Slint and Iced (used by cosmic), but they were in very early stages when i started this project, and they would still most likely be more out of place in terms of looks than gtk.
