### ISSUE TITLE
Vram clock strange behaviour

### ISSUE THREAD

**Issue by Positrone311** [ilya-zlobintsev/LACT#394]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation. Examples of known driver-side issues are fans not turning on with a custom curve or inaccurate power limits on RDNA3.
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

Hello, i noticed some weird things about the vram slider.

I set it to 2120mhz, however even when it is set to that, it'll still cap at 1060 when playing a game
![image](https://github.com/user-attachments/assets/b6c5abe4-403f-4375-b37c-7d3116a0a00b)
![image](https://github.com/user-attachments/assets/af81388b-d2ab-48d2-8ebf-1698e47e6c34)
![image](https://github.com/user-attachments/assets/9b1774ba-deb3-4e6c-9c47-681f4efa01fe)

If i slide it to 2150, which is the maximum, it will clock at 2075, so it's operating at 2000 + ((x-2000)/2)

Additionally, the application will show 2120 only if i boot my computer with only one monitor connected, if i boot it with both of my monitors (connected via displayport) the application shows the vram at 2060, and the slider maxes at 2075
![image](https://github.com/user-attachments/assets/3d070ef5-6da3-4084-ba41-70268e8b14b0)

In this image i have altered the gpu clock and voltage, but not the vram clock. 

### System info

```markdown
- LACT version: 0.5.6-release
- GPU model: AMD Radeon RX 6700 XT Sapphire Pulse
- Kernel version: 6.6.57-1-lts
- Distribution: EndeavourOS kde plasma
```

**Comment by ilya-zlobintsev** [comment]
The difference between LACT and mangohud is just due to reporting. The driver reports GDDR6 clocks at half the effective speed, LACT converts it to effective clocks so it lines up with listed hardware specs and the behaviour on windows. Mangohud likely just shows what the driver reports. 2120 cap / 2 = 1060, so it's correct.

> the application will show 2120 only if i boot my computer with only one monitor connected, if i boot it with both of my monitors (connected via displayport) the application shows the vram at 2060

I've never heard of such behaviour, but LACT does nothing of this sort so it's likely something your GPU does in the firmware. 

However in the bottom screenshot you have LACT showing 1060 MHz as well, which isn't correct as it's not doing the conversion. If you can tell me what steps you took before it shows the non-converted value that would be helpful

**Comment by Positrone311** [comment]
yes, i've misread the clock speed, 2060mhz was never displayed anywhere. LACT shows 1060 mhz when i boot my computer with 2 monitors plugged into my gpu. If i boot it with only one, it shows 2120 mhz

**Comment by Positrone311** [comment]
however, even when LACT displays 1060 mhz, mangohud still reports 1060mhz, meaning the effective clock speed is still correct.

**Comment by ilya-zlobintsev** [comment]
That does sound like very odd behaviour, could you tell me the following:
- When you boot with 2 monitors and it's showing you 1060 MHz as the clock, does the information page tell you that the VRAM type is GDDR6?
- What's the log of `journalctl -u lactd -e` when this happens?
- If you restart the service with `sudo systemctl restart lactd` and then check the values, does it still have 1060 in the GUI?

**Comment by Positrone311** [comment]
![image](https://github.com/user-attachments/assets/2bde718c-6d67-40bb-9155-0722910ff6ad)
the information page shows most things as unkown, this is when i boot with 2 monitors and clock is 1060mhz.

![image](https://github.com/user-attachments/assets/a37d3ed5-2f0d-4b5a-9dfe-371daf7be18f)
result of journalctl -u lactd -e

![image](https://github.com/user-attachments/assets/15214043-56c2-4893-baa4-75009931e6a2)
![image](https://github.com/user-attachments/assets/da0df1f7-7e65-49c8-a2c5-2c744c1d17f4)
sudo systemctl restart lactd fixed the incorrect display, and all the information is displayed correctly too, however there's another issue, now games flicker quite a bit, this also happens when i change a setting. A system restart fixes the flickering.

I Don't have another discrete gpu in my system. I have a ryzen 5 5600, so it shouldn't have integrated graphics AFAIK

**Comment by Positrone311** [comment]
Update: i restarted my system to fix the flickering, and now even though both monitors were connected, LACT is displaying  all information correctly, including vram clock.

**Comment by ilya-zlobintsev** [comment]
This looks like not something that's related to connected monitors, but rather a race condition at boot where LACT starts before the GPU is fully initialized, and isn't able to read the VRAM type because of it which is required for calculating the effective clockspeed.

I've increased the intervals for initializing GPUs at boot in https://github.com/ilya-zlobintsev/LACT/commit/d0f593e65542f1cdfe2e47e09b316bbade532d44. You can try the latest git version and see if the issue no longer occurs.

**Comment by Positrone311** [comment]
installed the git version and on first restart all is displayed correctly. I'll continue monitoring and report back if the issue returns.
